kind: Template
apiVersion: template.openshift.io/v1
labels:
  template: data-science-covid
message: |-
  The following service(s) have been created in your project: ${NAME}.
  For more information about using this template, including OpenShift considerations,
  see https://github.com/netappspain/webinar-trident/blob/master/templates/data-science-covid.yaml.
metadata:
  name: data-science-covid
  annotations:
    tags: data-science-covid
    description: A simple web server which shows some CSV files cloning an existing persistent volume.
      For more information about using this template, including OpenShift considerations,
      see https://github.com/netappspain/webinar-trident/blob/master/templates/data-science-covid.yaml.
    iconClass: icon-linux
    openshift.io/display-name:  A simple web server which shows some CSV files cloning an existing persistent volume.
    openshift.io/documentation-url: https://github.com/netappspain/webinar-trident/blob/master/templates/data-science-covid.yaml
    openshift.io/long-description: A simple web server which shows some CSV files cloning an existing persistent volume.
    openshift.io/provider-display-name: Pablo Garcia Arevalo
objects:

- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: ${NAME}
    name: ${NAME}
    namespace: ${NAMESPACE}
  spec:
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: ${NAME}
      weight: 100

- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: ${NAME}
    name: ${NAME}
    namespace: ${NAMESPACE}
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: ${NAME}
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: ${NAME}
          deploymentconfig: ${NAME}
      spec:
        containers:
        - image: bitnami/nginx:latest
          imagePullPolicy: Always
          name: ${NAME}
          ports:
          - containerPort: 8080
            protocol: TCP
          volumeMounts:
            - name: my-pvc
              mountPath: /app
        volumes:
        - name: my-pvc
          persistentVolumeClaim:
            claimName: ${NAME}

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: ${NAME}
    namespace: ${NAMESPACE}
  spec:
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 100Ti
    storageClassName: nas
    dataSource:
      name: snap-datalake
      kind: VolumeSnapshot
      apiGroup: snapshot.storage.k8s.io

- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${NAME}
    name: ${NAME}
    namespace: ${NAMESPACE}
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: ${NAME}
      deploymentconfig: ${NAME}
    sessionAffinity: None
    type: ClusterIP

parameters:
- description: The name assigned to all of the objects defined in this template.
  displayName: Name
  name: NAME
  required: true
  value: data-science-
- description: The namespace where objects will run.
  displayName: NAMESPACE
  name: NAMESPACE
  required: true
  value: 4-webinar
  